services:
  web:
    build: ./app/php
    container_name: gestion-produits-web
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app/php/www:/var/www/html
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: gestion-produits-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_postgres:/var/lib/postgresql/data
      - ./app/database/gestion_produits_pg.sql:/docker-entrypoint-initdb.d/gestion_produits.sql

volumes:
  db_data_postgres:
