# -------------------------------------------------------------------
# App PHP + MySQL (version "production")
# -------------------------------------------------------------------

services:
  web:
    build: ./app/php
    container_name: gestion-produits-web
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app/php/www:/var/www/html
    env_file:
      - .env

  db:
    image: mysql:8.4
    container_name: gestion-produits-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_mysql:/var/lib/mysql
      - ./app/database/gestion_produits.sql:/docker-entrypoint-initdb.d/gestion_produits.sql

volumes:
  db_data_mysql:
