apiVersion: v1
kind: Service
metadata:
  name: php-mysql
  namespace: gestion-produits
spec:
  selector:
    app: php-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
