name: Build and Push Docker image

on:
  push:
    branches:
      - mysql
      - postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./app/php
          push: true
          tags: ghcr.io/${{ github.repository }}/gestion-produits-php-mysql:latest